server.port=8080

management.endpoints.web.exposure.include=*

management.endpoint.env.show-values=ALWAYS
management.endpoint.configprops.show-values=ALWAYS

debug=true

server.error.include-stacktrace=always
