services:

  db:
    image: mysql:8.0
    container_name: a01_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medtrack
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: ./web
    container_name: a01_web
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: medtrack